config/routes.rb
Rails.application.routes.draw do
   devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index]

  resources :tracks, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :races, only: [:show, :create, :destroy]
    resources :messages, only: [:create]
  end
  get "/tests/get_test", to: "tests#get_test"
  resources :races, only: [:destroy] do
    member do
      post 'start_running'
    end
    #collection do
      #post "strava_api"
    #end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # validates :username, uniqueness: true


  has_many :races, dependent: :destroy
  has_many :tracks, through: :races
  has_many :messages, dependent: :destroy




  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:strava]

 has_one_attached :photo # Cloudinary

 #  # we will let the geocode access our address and convert it to latitude and longitude. #mapbox
 #  geocoded_by :address
 #  after_validation :geocode, if: :will_save_change_to_address?

  def self.find_for_strava_oauth(auth)
    # 1) assign correct values to the keys that are missing in user info hash
    # 2) find in the documentation of strava what is the scope that allows us to do everything, full permission, all info
    # 3) kill the server after changing the devise rb file
    # 4) open server and log in again, chacking what is now inside the auth variable
    user_info = {
      uid: auth["uid"],
      provider: auth["provider"],
      token: auth["credentials"]["token"],
      name: auth["info"]["name"],
      refresh_token: auth["credentials"]["refresh_token"],
      token_expiry: auth["credentials"]["exipires_at"],
      profile_img_url: auth["extra"]["raw_info"]["profile"]
    }

    user = User.find_by(provider: user_info[:provider], uid: user_info[:uid])
    if user
      user.update(user_info)
    else
      user = User.new(user_info)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save(validate: false)
    end

    return user
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def strava
    user = User.find_for_strava_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Strava') if is_navigational_format?
    else
      session['devise.strava_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   # def update
    # super
   # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show]

  def index
    @users = User.all
  end

  def show

    @races = Race.where(user_id: @user.id)

    @raceopen = []
    @raceclose = []

    @races.each do |race|
      track = Track.find(race.track_id)
      if track.status == 'open'
        @raceopen << race
      else
        @raceclose << race

      end
    end
    # authorize @user

    # @markers = [{
    #   lat: @user.latitude,
    #   lng: @user.longitude,
    #   infoWindow: render_to_string(partial: "info_window", locals: { user: @user }),
    #   image_url: helpers.asset_url('logo.png')
    # }]
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user_path(user) do %>
    <%= user.name %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div data-aos="fade-up"
     data-aos-duration="3000"
     class="profile-page">
  <%= image_tag "profile-background.jpg" , width: "100%", class: "hovercard" %>


  <div class="profile-avatar">
    <%= cl_image_tag @user.photo.key, crop: :fill, 'aria-haspopup': true, 'aria-expanded': false if @user.photo.attached?%>
    <%= image_tag "avatar-default-copy.png", crop: :fill, 'aria-haspopup': true, 'aria-expanded': false unless @user.photo.attached?%>
  </div>

  <div class="profile-info">
      <h1><%= @user.username.capitalize %></h1>

      <div class=profile-small-info>
          <div class="profile-races-number">
            <p>
              <i class="fas fa-running"></i>
              Races number:
              <% if @user.races_number == nil %>
                0
              <% else %>
                <%=  @user.races_number %>
              <% end %>
            </p>
          </div>
            <div class="profile-user-level">
              <p>Level: <%= @user.level %></p>
            </div>
      </div>
        <div class="btn btn-primary">
          <%= link_to "Create your own Race", new_track_path %>
        </div>
  </div>

  <div class="profile-botton-part">

    <div class="personal-info">
        <div class="card-body">
          <p>About me: <%= @user.Bio.capitalize if @user.Bio %></p>
          <%= link_to edit_user_registration_path, class: "nav-link" do %>
          <i class="fas fa-user-edit"></i>
          <% end %>
        </div>
    <div class="profile-races-cards">
      <div class="past-races">
        <div data-aos='fade-up' class="card bg-light mb-3">
          <div  class="card-header">
            <h2>Past Races</h2>
          </div>
          <div class="card-body">
            <% @raceclose.each do |race|%>
              <% track = Track.find(race.track_id) %>
              <%= link_to track_path(track) do%>
                <%=  track.name %>
                <br>
              <% end %>
            <% end %>
          </div>
        </div>
    </div>
      </div>

      <div class="profile-races">
        <div class="profile-schedule-race">
          <div data-aos='fade-up' class="card bg-light mb-3">
            <div class="card-header">
              <h2>Scheduled Races</h2>
            </div>

            <div class="card-body">
              <% @raceopen.each do |race|%>
                <% track = Track.find(race.track_id) %>
                <%= link_to track_path(track) do%>
                  <%=  track.name %>
                  <br>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>