config/routes.rb
Rails.application.routes.draw do
   devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index]

  resources :tracks, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :races, only: [:show, :create, :destroy]
    resources :messages, only: [:create]
  end
  get "/tests/get_test", to: "tests#get_test"
  resources :races, only: [:destroy] do
    member do
      post 'start_running'
    end
    #collection do
      #post "strava_api"
    #end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<div class="menu fixed-bottom">

  <div class="menu-links">



    <% if request.fullpath == tracks_path %>

      <%= link_to tracks_path, class: 'btn btn-secondary  menu-icon' do %>
        <i class="fas fa-home"></i>
      <% end %>
    <% else %>
      <%= link_to tracks_path, class: 'btn btn-light menu-icon' do %>
        <i class="fas fa-home"></i>
      <% end %>
    <% end %>




    <% if current_user %>
      <% if request.fullpath == user_path(current_user) %>
        <%= link_to user_path(current_user), class: 'btn btn-secondary  menu-icon'   do %>
          <i class="fas fa-running"></i>
        <% end %>
      <% else %>
        <%= link_to user_path(current_user), class: 'btn btn-light menu-icon'   do %>
          <i class="fas fa-running"></i>
        <% end %>
      <% end %>
    <% end %>



  <% if request.fullpath == new_track_path %>
    <%= link_to new_track_path, class: 'btn btn-secondary menu-icon' do %>
      <i class="fa fa-plus" aria-hidden="true"></i>
    <% end %>
  <% else %>
    <%= link_to new_track_path, class: 'btn btn-light menu-icon' do %>
      <i class="fa fa-plus" aria-hidden="true"></i>
    <% end %>
  <% end %>

  </div>
</div>




    <!-- <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
 -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", crop: :fill %>
    <% end %>



      <% if user_signed_in? %>
        <ul class='navbar-list'>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false if current_user.photo.attached?%>
            <%= image_tag "avatar-default-copy.png", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false unless current_user.photo.attached?%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Tracks", tracks_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      <% else %>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link-login" %>
        </li>
      <% end %>
</div>